### ISSUE TITLE
Image is uploaded but it doesnt show and it can't find the url

### ISSUE THREAD

**Issue by Rovel** [bradleyg/django-ajaximage#14]
Please, help me to implement the Ajaximage, it seems that is cant find the url, the file is stored in the proper folder, but the admin and the view cant find the image...
# Project Setting:(does it need some django.contrib app??)

INSTALLED_APPS = (
 ....
    'ajaximage',
.....

MEDIA_URL = 'media/'
MEDIA_ROOT = 'media/'

STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'

AJAXIMAGE_DIR = 'media/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
# Project URL:

urlpatterns = patterns('',
url(r'^ajaximage/', include('ajaximage.urls')),
# Images App URL:

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
# Images App Admin:

from django.contrib import admin

from Images.models import Image
from ajaximage.fields import AjaxImageField

admin.site.register(Image)
# Images App model:

from django.db import models

from ajaximage.fields import AjaxImageField

class Image(models.Model):
    titulo = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('date published')
    thumbnail = AjaxImageField(upload_to='thumbnails',
                               max_height=200, #optional
                               max_width=200, # optional
                               crop=True) # optional
    def **unicode**(self):  # Python 3: def **str**(self):
        return self.titulo
    def was_published_recently(self):
        return self.data_publicacao >= timezone.now() - datetime.timedelta(days=1)
    def get_absolute_url(self):
        return reverse('Image:detail', kwargs={'pk': self.pk})
# Admin Interface:

![captura de tela 2014-08-25 as 23 32 49](https://cloud.githubusercontent.com/assets/2469500/4039337/796b1e08-2cc9-11e4-9347-79c0af3ae5c1.png)
# Admin image url:

![captura de tela 2014-08-25 as 23 35 18](https://cloud.githubusercontent.com/assets/2469500/4039358/014f800c-2cca-11e4-80ad-aaf65f4851e4.png)
# View index:

![captura de tela 2014-08-25 as 23 56 42](https://cloud.githubusercontent.com/assets/2469500/4039502/a5d6b3c8-2ccc-11e4-9a93-037213376834.png)

Thanks!

**Comment by int-ua** [comment]
Another reason for such behavior is that media is not served: http://stackoverflow.com/a/10955068
